### ISSUE TITLE
目标

### ISSUE THREAD

**Issue by liuxyon** [EthanOrange/tv#26]
新来的,我还不知道这个程序怎么安装在自己服务器提供服务,另外这个程序目标是什么?
我是正在找在线TV 和视频点播. 例如支持卫星电视直播 点播 回放等等功能 和一些电影等点播,另外外围增加社交 赞助等.  它是否支持高清播放,例如htl  ts最好使用自己内嵌的播放器和编码.  
有完整手册吗?

**Comment by 3lang3** [comment]
@liuxyon  抱歉这个只是一个聚合web应用  并不输出视频源 只是爬取网路上的视频源 也就是一个展示平台而已

**Comment by liuxyon** [comment]
我知道,我的意思如果我有直播链接地址是可以支持高清播放?  不只是游戏? 另外怎么安装到web服务器?我目前使用IIS10

**Comment by 3lang3** [comment]
@liuxyon  只要源那边不限制的话 都可以播放的  
安装的话 IIS10不支持哦，需要安装[nodejs(8.0+)](http://nodejs.org) 然后按照readme操作就能本地预览
